import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Suspense } from 'react';
import './globals.css';
import Sidebar from '@/components/Sidebar';
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background flex`}
      >
        <Suspense
          fallback={<div className="w-72 border-r border-brand-light/30 bg-slate-50" />}
        >
          <Sidebar />
        </Suspense>
        <main className="flex-1 ml-72 min-h-screen">{children}</main>
      </body>
    </html>
  );
}
